import "server-only";
import { GoogleGenerativeAI } from "@google/generative-ai";

export async function evaluateStudentSubmission(
  scenarioTitle: string,
  scenarioDescription: string,
  constraints: string[],
  studentDraft: string
): Promise<{
  passed: boolean;
  feedback: string;
  failedConstraints: string[];
  isAiGenerated?: boolean;
  aiDetectionReason?: string;
}> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    // Fallback if no API key is provided
    return {
      passed: true,
      feedback: "Development mode: AI evaluation skipped (No API key configured). Assuming passed.",
      failedConstraints: [],
      isAiGenerated: false,
    };
  }

  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({ model: "gemini-3.5-flash" });

  const prompt = `
You are a strict academic evaluator assessing a student's civic action plan based on a given scenario and specific constraints.

Scenario Title: "${scenarioTitle}"
Scenario Description: "${scenarioDescription}"

Constraints that MUST be met:
${constraints.map((c, i) => `${i + 1}. ${c}`).join("\n")}

Student's Submitted Draft:
"""
${studentDraft}
"""

EVALUATION CRITERIA (BE STRICT):

1. GIBBERISH & LOW-EFFORT CHECK:
   - Immediately REJECT (passed = false) if the text contains random characters (e.g., "sfsfdf", "tytyt", "asdf"), single-word responses ("yes", "ok"), or nonsensical key mashes.

2. STRICT CONSTRAINT FULFILLMENT:
   - Every single constraint listed above must be explicitly and substantively addressed in realistic detail.
   - Vague, generic, or off-topic statements DO NOT pass. The student must explain HOW, WHO, or WHAT specific steps will be taken.
   - If ANY constraint is missing, incomplete, or insufficiently detailed, set passed = false and include the exact constraint text in "failedConstraints".

3. AI DETECTOR & ORIGINALITY CHECK:
   - Analyze the writing style for strong indicators of AI generation (e.g., typical LLM phrases like "In conclusion", "Furthermore, it is crucial to emphasize...", over-polished generic bullet points, or copy-pasted AI output without authentic student voice).
   - If the text strongly appears to be generated by an AI assistant, set "isAiGenerated" = true and explain why in "aiDetectionReason".
   - If AI generation is detected, "passed" MUST be set to false.

Respond STRICTLY in valid JSON with no extra text:
{
  "passed": boolean,
  "isAiGenerated": boolean,
  "aiDetectionReason": "string (empty string if genuine student writing, otherwise explain why it appears AI generated)",
  "failedConstraints": ["string (list the exact constraints that were missed or insufficiently addressed)"],
  "feedback": "string (Constructive feedback addressed directly to the student explaining what was good or what needs to be revised in their own words.)"
}
`;

  try {
    const result = await model.generateContent(prompt);
    const responseText = result.response.text();
    
    // Extract JSON block in case there's markdown formatting or extra text
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    const jsonString = jsonMatch ? jsonMatch[0] : responseText;

    const parsed = JSON.parse(jsonString);

    const isAi = Boolean(parsed.isAiGenerated);
    const failedList: string[] = Array.isArray(parsed.failedConstraints) ? parsed.failedConstraints : [];
    const passed = Boolean(parsed.passed) && !isAi && failedList.length === 0;

    let finalFeedback = parsed.feedback || "Please review and revise your response.";
    if (isAi) {
      finalFeedback = `[AI Content Detected] ${parsed.aiDetectionReason || "This response appears to be generated by AI."}\n\nPlease write your civic action plan in your own original words.`;
    }

    return {
      passed,
      feedback: finalFeedback,
      failedConstraints: failedList,
      isAiGenerated: isAi,
      aiDetectionReason: parsed.aiDetectionReason || "",
    };
  } catch (error) {
    console.error("AI Evaluation Error:", error);
    return {
      passed: false,
      feedback: `AI Evaluation Error: ${error instanceof Error ? error.message : String(error)}. Please try again.`,
      failedConstraints: [],
      isAiGenerated: false,
    };
  }
}
